# Generated by Django 5.0.1 on 2024-01-27 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('src_addr', models.CharField(max_length=100)),
                ('dst_addr', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Confirm'), (3, 'Complete')], default=1)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('time_uptate', models.TimeField(auto_now=True)),
                ('time_complete', models.TimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'ride',
                'verbose_name_plural': 'rides',
            },
        ),
    ]
